server:
  port: 8080


spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/spring_social?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
    thymeleaf:
      cache: false

my:
  social:
    qq:
      app-id: 100550231
      app-secret: eag
    weixin:
      app-id: wx645c3f3ece77477d
      app-secret: 54caaa2d2cf76f77675b733d42ec2be2
      scope: snsapi_login
logging.level.org.springframework.security: DEBUG